name: R
on:
  push:
    branches: master
  workflow_dispatch:
    branches: master
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Render the rmarkdown file into rmd/
      - name: run Rscript
        shell: Rscript {0}
        run: Rscript news_api_script.R
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY}}
